### ISSUE TITLE
old todo list from week 3-8

### ISSUE THREAD

**Issue by alex9311** [alex9311/Information-Retrieval#24]
@HDking 
###### Week 3
- [x] finalized idea (group)
- [x] practice/prepare pitch (Peter/Hao)
- [x] finalizing elaborating idea document (group)
  - [x] Relevance to course (Peter)
  - [x] Innovative and challenges (Miriam)
  - [x] Requirements specifications (gizem)
  - [x] UML design (Hao)
  - [x] planned eval and success metrics (mon/tues next week)
  - [x] Review document
- [x] bluemix server and git setup (Alex)
- [x] Maybe start on DB schema (Alex)
- [x] visuals and front end (picking css library, making user interface) (Miriam Gizem)
- [x] check out crowdflower, design what is necessary (Gizem, Miriam)
- [x] Check out Lucene (Peter Hao)
###### Week 4
- [x] build DB schema and implement, with php interface to update it
- [x] build functionality to upload pictures with text
- [ ] functionality to login as user
##### Week 5 deadlines
- [ ] user be able to login and submit ideas that are stored
  - [ ] be able to send out link to contribute
  - [x] have DB running, linked to front end
##### Week 6 deadlines
- [x] app ready for crowdflower usage
- [ ] the IR similarity check
  - [ ] understanding lucene and implementing it
##### Week7 deadlines
- [x] user voting implementation
- [ ] finalize front end
- [x] having voting working
##### Week 8 deadlines
- [ ] everything is done

**Comment by HDking** [comment]
it's web-app building time!

**Comment by millenniumproof** [comment]
I'm taking the day off :p
I guess we should decide on who does what.

**Comment by HDking** [comment]
Yes! 
For me: I will not be in the country for a couple of days (from tomorrow to Sunday). Shall we meet on Monday and agree on what we want to do and stuff?

**Comment by millenniumproof** [comment]
I have some work to do today on a different project, so I'm staying home. I can work on the implementation tomorrow. I can look into the Facebook login, image uploading or database schema.

**Comment by HDking** [comment]
@GizKockesen shall we look into the front-end design tomorrow?

**Comment by alex9311** [comment]
Yeah we still need to choose a front end framework or template

**Comment by HDking** [comment]
Im still down for playing around with [Semantic-UI](http://semantic-ui.com/modules/transition.html). Next to all kinds of User Interface elements, it contains all kinds of behaviours / transitions that could be nice (where the link is heading). It does not have any templates, but its mostly a user interface framework.  I'm not really sure why we could not make some nice layout ourselfs? Alex does Semantic-UI has a chance to be implemented with the back-end?

**Comment by alex9311** [comment]
Semantic-UI would probably work great, sounds good to me! We'd probably hook it into the database with PHP

**Comment by GizKockesen** [comment]
I've been working on the template so I can put it up by tonight :)

**Comment by HDking** [comment]
cool!
